// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInvest.Infrastructure.Data;

#nullable disable

namespace SmartInvest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ContractType", b =>
                {
                    b.Property<int>("ContractTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractTypeId"));

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractTypeId");

                    b.ToTable("ContractType");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NationalIdOrCommercialRegister")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractorId");

                    b.ToTable("Contractor");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.DelayReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DelayReason");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ExecutiveAgency", b =>
                {
                    b.Property<int>("ExecutiveAgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExecutiveAgencyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExecutiveAgencyId");

                    b.ToTable("ExecutiveAgency");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.FinancialYear", b =>
                {
                    b.Property<int>("FinancialYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialYearId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FinancialYearId");

                    b.ToTable("FinancialYear");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Governorate", b =>
                {
                    b.Property<int>("GovernorateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GovernorateId"));

                    b.Property<string>("GovernorateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GovernorateId");

                    b.ToTable("Governorate");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.InvestmentProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InvestmentProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.MainProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramId");

                    b.ToTable("MainProgram");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.MainProject", b =>
                {
                    b.Property<int>("MainProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MainProjectId"));

                    b.Property<string>("ExecutingAgency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MainProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubProgramId")
                        .HasColumnType("int");

                    b.HasKey("MainProjectId");

                    b.HasIndex("MainProjectCode")
                        .IsUnique()
                        .HasFilter("[MainProjectCode] IS NOT NULL");

                    b.HasIndex("SubProgramId");

                    b.ToTable("MainProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Markaz", b =>
                {
                    b.Property<int>("MarkazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkazId"));

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("MarkazName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkazId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Markaz");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanId");

                    b.HasIndex("FinancialYearId");

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.PlanProject", b =>
                {
                    b.Property<int>("PlanProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanProjectId"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("SubProjectId")
                        .HasColumnType("int");

                    b.HasKey("PlanProjectId");

                    b.HasIndex("PlanId");

                    b.HasIndex("SubProjectId");

                    b.ToTable("PlanProject");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ContractorId")
                        .HasColumnType("int");

                    b.Property<int>("ExecutiveAgencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubProjectId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("ContractorId");

                    b.HasIndex("ExecutiveAgencyId");

                    b.HasIndex("SubProjectId");

                    b.ToTable("ProjectAssignment");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowUpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("FollowUpId");

                    b.ToTable("ProjectAttachment");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectFollowUp", b =>
                {
                    b.Property<int>("FollowUpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowUpId"));

                    b.Property<int?>("DelayReasonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("FollowUpId");

                    b.HasIndex("DelayReasonId");

                    b.HasIndex("PlanProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("ProjectFollowUp");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectPriority");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SpecificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubProjectId");

                    b.ToTable("ProjectSpecification");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("ProjectStatus");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.SubProgram", b =>
                {
                    b.Property<int>("SubProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubProgramId"));

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("SubProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("SubProgram");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.SubProject", b =>
                {
                    b.Property<int>("SubProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubProjectId"));

                    b.Property<string>("AccountingUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BankFunding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EconomicImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentalImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GreenInvestmentLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MainProjectId")
                        .HasColumnType("int");

                    b.Property<int>("MarkazId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SelfFunding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SocialImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("SubProjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubProjectId");

                    b.HasIndex("MainProjectId");

                    b.HasIndex("MarkazId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SubProjectCode")
                        .IsUnique()
                        .HasFilter("[SubProjectCode] IS NOT NULL");

                    b.ToTable("SubProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Village", b =>
                {
                    b.Property<int>("VillageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VillageId"));

                    b.Property<int>("MarkazId")
                        .HasColumnType("int");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VillageId");

                    b.HasIndex("MarkazId");

                    b.ToTable("Village");
                });

            modelBuilder.Entity("SmartInvest.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartInvest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartInvest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartInvest.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.MainProject", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.SubProgram", "SubProgram")
                        .WithMany("MainProjects")
                        .HasForeignKey("SubProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubProgram");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Markaz", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.Governorate", "Governorate")
                        .WithMany("Marakez")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Plan", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.FinancialYear", "FinancialYear")
                        .WithMany("Plans")
                        .HasForeignKey("FinancialYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialYear");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.PlanProject", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanProjects")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvest.Domain.Entities.SubProject", "SubProject")
                        .WithMany("PlanProjects")
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectAssignment", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.ContractType", "ContractType")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvest.Domain.Entities.Contractor", "Contractor")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("ContractorId");

                    b.HasOne("SmartInvest.Domain.Entities.ExecutiveAgency", "ExecutiveAgency")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("ExecutiveAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvest.Domain.Entities.SubProject", "SubProject")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractType");

                    b.Navigation("Contractor");

                    b.Navigation("ExecutiveAgency");

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectAttachment", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.ProjectFollowUp", "ProjectFollowUp")
                        .WithMany("Attachments")
                        .HasForeignKey("FollowUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectFollowUp");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectFollowUp", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.DelayReason", "DelayReason")
                        .WithMany("ProjectFollowUps")
                        .HasForeignKey("DelayReasonId");

                    b.HasOne("SmartInvest.Domain.Entities.PlanProject", "PlanProject")
                        .WithMany("ProjectFollowUps")
                        .HasForeignKey("PlanProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartInvest.Domain.Entities.ProjectStatus", "Status")
                        .WithMany("ProjectFollowUps")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DelayReason");

                    b.Navigation("PlanProject");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectSpecification", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.SubProject", "SubProject")
                        .WithMany("ProjectSpecifications")
                        .HasForeignKey("SubProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubProject");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.SubProgram", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.MainProgram", "MainProgram")
                        .WithMany("SubPrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainProgram");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.SubProject", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.MainProject", "MainProject")
                        .WithMany("SubProjects")
                        .HasForeignKey("MainProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInvest.Domain.Entities.Markaz", "Markaz")
                        .WithMany("SubProjects")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInvest.Domain.Entities.ProjectPriority", "Priority")
                        .WithMany("SubProjects")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartInvest.Domain.Entities.ProjectStatus", "Status")
                        .WithMany("SubProjects")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainProject");

                    b.Navigation("Markaz");

                    b.Navigation("Priority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Village", b =>
                {
                    b.HasOne("SmartInvest.Domain.Entities.Markaz", "Markaz")
                        .WithMany("Villages")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Markaz");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ContractType", b =>
                {
                    b.Navigation("ProjectAssignments");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Contractor", b =>
                {
                    b.Navigation("ProjectAssignments");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.DelayReason", b =>
                {
                    b.Navigation("ProjectFollowUps");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ExecutiveAgency", b =>
                {
                    b.Navigation("ProjectAssignments");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.FinancialYear", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Governorate", b =>
                {
                    b.Navigation("Marakez");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.MainProgram", b =>
                {
                    b.Navigation("SubPrograms");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.MainProject", b =>
                {
                    b.Navigation("SubProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Markaz", b =>
                {
                    b.Navigation("SubProjects");

                    b.Navigation("Villages");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.PlanProject", b =>
                {
                    b.Navigation("ProjectFollowUps");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectFollowUp", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectPriority", b =>
                {
                    b.Navigation("SubProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.ProjectStatus", b =>
                {
                    b.Navigation("ProjectFollowUps");

                    b.Navigation("SubProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.SubProgram", b =>
                {
                    b.Navigation("MainProjects");
                });

            modelBuilder.Entity("SmartInvest.Domain.Entities.SubProject", b =>
                {
                    b.Navigation("PlanProjects");

                    b.Navigation("ProjectAssignments");

                    b.Navigation("ProjectSpecifications");
                });
#pragma warning restore 612, 618
        }
    }
}
